### ISSUE TITLE
Design Improvements 

### ISSUE THREAD

**Issue by illusiveCode** [illusiveCode/quote-generator#1]
- [x] Add new fonts for the whole html document
- [x] Change colors 
- [x] Add animations/transitions

**Comment by AtharvaParkale** [comment]
I would like to work on this issue

**Comment by illusiveCode** [comment]
> I would like to work on this issue

Yes, you absolutely can contribute. Go ahead and fork the repo and propose your ideas!

**Comment by AtharvaParkale** [comment]
> > I would like to work on this issue
> 
> Yes, you absolutely can contribute. Go ahead and fork the repo and propose your ideas!

Do you want to just the animations, or color and font too?

**Comment by illusiveCode** [comment]
> > > I would like to work on this issue
> > 
> > Yes, you absolutely can contribute. Go ahead and fork the repo and propose your ideas!
> 
> Do you want to just the animations, or color and font too?

The color and font too, please.
